(function() {var implementors = {};
implementors["abomonation"] = [{text:"impl&lt;T, S:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.DerefMut.html\" title=\"trait core::ops::deref::DerefMut\">DerefMut</a>&lt;Target = <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.slice.html\">[</a><a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a><a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.slice.html\">]</a>&gt;&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"abomonation/abomonated/struct.Abomonated.html\" title=\"struct abomonation::abomonated::Abomonated\">Abomonated</a>&lt;T, S&gt;",synthetic:false,types:["abomonation::abomonated::Abomonated"]},];
implementors["timely"] = [{text:"impl&lt;'a, T:&nbsp;<a class=\"trait\" href=\"timely/order/trait.PartialOrder.html\" title=\"trait timely::order::PartialOrder\">PartialOrder</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"timely/progress/frontier/struct.AntichainRef.html\" title=\"struct timely::progress::frontier::AntichainRef\">AntichainRef</a>&lt;'a, T&gt;",synthetic:false,types:["timely::progress::frontier::AntichainRef"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"timely/progress/timestamp/trait.Timestamp.html\" title=\"trait timely::progress::timestamp::Timestamp\">Timestamp</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"timely/dataflow/operators/struct.Capability.html\" title=\"struct timely::dataflow::operators::Capability\">Capability</a>&lt;T&gt;",synthetic:false,types:["timely::dataflow::operators::capability::Capability"]},{text:"impl&lt;'cap, T:&nbsp;<a class=\"trait\" href=\"timely/progress/timestamp/trait.Timestamp.html\" title=\"trait timely::progress::timestamp::Timestamp\">Timestamp</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"timely/dataflow/operators/struct.CapabilityRef.html\" title=\"struct timely::dataflow::operators::CapabilityRef\">CapabilityRef</a>&lt;'cap, T&gt;",synthetic:false,types:["timely::dataflow::operators::capability::CapabilityRef"]},];
implementors["timely_bytes"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"timely_bytes/rc/struct.Bytes.html\" title=\"struct timely_bytes::rc::Bytes\">Bytes</a>",synthetic:false,types:["timely_bytes::rc::Bytes"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"timely_bytes/arc/struct.Bytes.html\" title=\"struct timely_bytes::arc::Bytes\">Bytes</a>",synthetic:false,types:["timely_bytes::arc::Bytes"]},];
implementors["timely_communication"] = [{text:"impl&lt;'a, T:&nbsp;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"enum\" href=\"timely_communication/message/enum.RefOrMut.html\" title=\"enum timely_communication::message::RefOrMut\">RefOrMut</a>&lt;'a, T&gt;",synthetic:false,types:["timely_communication::message::RefOrMut"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"timely_communication/message/struct.Message.html\" title=\"struct timely_communication::message::Message\">Message</a>&lt;T&gt;",synthetic:false,types:["timely_communication::message::Message"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
